services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.1
    container_name: etcd
    ports:
    - 2379:2379
    environment:
       - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
       - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    volumes:
      - etcd-data:/etcd-data