services:
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    ports:
      - 2379:2379
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd-data:/etcd-data
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
  registry-service:
    build:
      context: .
    environment:
      - ETCD_HOST=http://etcd:2379
    container_name: RegistryService
    ports:
      - 3003:3003
    depends_on:
      - etcd
    networks:
      - shared-network

networks:
  shared-network:
    external: true
volumes:
  etcd-data: {}
