FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npx tsc 

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/dist /app
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/node_modules /app/node_modules

CMD ["node", "./transport/Account-Adapter.js"]