services:
  database:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pg-data:/var/lib/postgres/sql/data
  pgadmin:
    image: dpage/pgadmin4:8.3
    ports:
      - 80:80
    volumes:
      - ./pg-admin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: beispiel@beispiel.de 
      PGADMIN_DEFAULT_PASSWORD: beispiel123
    depends_on:
      - database


