services:
  lending:
    image: postgres:16.2
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: lending
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pg-data:/var/lib/postgres/sql/data
