services:
  inventorydb:
    image: postgres:16.2
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pg-data:/var/lib/postgres/sql/data
    networks:
      - shared-network
  inventory-service:
    build:
      context: ../
    container_name: InventoryService
    ports:
      - 3001:3001
    depends_on:
      - inventorydb
    networks:
      - shared-network
networks:
  shared-network:
    external: true

